<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/styles/style.css"> <!-- Link to external CSS -->
    <link rel="icon" href="/images/favicon.ico" type="image/x-icon"> <!-- Add favicon here -->
</head>
<body class="blog-post-page"> 
    <div class="content">
        <?php include '../header.php'; ?> 
        <h1 class="underlined-heading">airplane fiction</h1>
        <div>
            <p>published 4 august 2023</p>
        </div>
        <img src="/images/air.jpg" alt="air" class="styled-image">

        <p>i woke up to the coldest sweat of my life, shivering as i hurried to fetch my gown from the wardrobe. the air was borderline moist, likely from the shutters being cracked. I always knew this damned cottage had its moments, albeit some better than others. Unfortunately ,in pertinence to my quality of sleep, it would indeed be lacking. I slip on my gown, its silk feel is cool on my soiled skin. i think to myself, “fuck”, another shifty dreamscape, as i try to recall what all the commotion in my head was about. as i reach the bottom of the stairwell, i can see that it is indeed first light outside, and that i ought to begin my dailies. I head to the cellar first to fetch last nights milk, (likely buttermilk now) to start the grueling day of foraging off right. i reach the base of the stairs, and in the same wake of air i felt as i awoke, something feels rightfully off. I grab the cool glass and head upstairs, pondering about all the rubbish of the day that is to ensue. I do wish I had company in these times, but i cant bare the thought of companionship after Lillian damned herself to hell. I am still VERY bitter, i will admit that. I often wonder if i will grow old here, or if i will pick it all up again and brave it elsewhere. We used to brave it more, really we all did. I suppose that’s what i miss about Lillian the most, her attitude toward it all. i cant help but think about last summer,  and wonder why god punished me. Why did god punish me, such a docile and disciplined man, i came from good family, ive done everything right but why would god punish me…? life is so unfair sometimes, but anyone can get used to negative personal change with enough time. “fuck” i think to myself again, as i found myself wasting the time away, in disheveled thought over Lillian and times of the past summer.</p>
        <p>I hurried off to the first task of the morning, milking the heifers. twice a day, papa always said, once at first light, and once after supper. Thankfully i only two to worry about now, and considering my fondness of dairy and the like, i have zero problems using all of their milk before it spoils. Next i collect the eggs from the henhouse. Papa always said to check for eggs three times a week, but in my solemness I have been eagerly checking daily, sometimes ever bi-daily. I even gave the sweet hen a name, Margie, i think of her as a friend. I give her life and she gives me food in return, an equal trade in my eyes, but oh! what do i know? the last of the morning chores is to fetch the daily pail. I was told last spring that the well on these grounds was tapped long before Vale was settled up north, so they know the supply is bountiful. I lower the pail but suddenly, the wind drops, breaking any sort of concentration i had. . i pan my gaze to the gorge and eerily enough, I notice something ive never seen before. awestruck, im rightfully awestruck at what im seeing. A gown, much alike my own nightgown, flowing in the (wind), yet there is none. My eyes follow the figure from the ground up, as my perplexed mind tries to make sense of what i am seeing. am i still dreaming? Why did i see her in my dreams, and why does this feel so strange? I continue my stare as the figure, seemlingly a woman, almost angel like, glows one of the most beautiful hues i have ever seen. Awestruck, really i am dumbfounded at this. “Am i dreaming?,” I ask myself again, and before i can break my thought, she’s gone.</p>
        <p>a couple of days had passed since i saw that figure, and i honestly cant seem to shake the thought. my nightmares, my nightmares that in hindsight were just her, and they weren’t nightmares at all. But my fucking god, does it make me want to rip my hair out. I cant fucking describe it, singlehandedly one of the most beautiful experiences of my life and yet the most frightening. Am i dreaming? oh, have i told you that i saw her again? and this time i tried to get closer to her, to see where she was off too, or maybe i could see her off, to wherever she was going, right? Am i wrong to think such things? I know Lilian isn’t around but, oh, is that her i see again? What is her name? What could her name be….? Is this a dream? When did i last milk the cows? Why is my gown on? Why is it all so painful now, oh the drag of this life, it really takes a hold of you, and no man should have to bare the worst of this alone. I need a farmhand, i need a friend, I need Lillian or …. Why is my gown on? Where am i? I turn my head around 200 degrees as i realize i do not recognize my surroundings, but the one thing i do recognize is the luminous gown, maybe a couple minutes walk down by the gorge again. Oh wait! The gorge! foolish, me, i must be dreaming, right? Where are my shoes…? I almost cant make a decision now, I HAVE to follow the light. Oh Lillian, i am so sorry my dear Lillian, i really wish it all went so different. Oh but the light i see now! How beautiful, and how kind, but my headaches, my headaches and growing so long and dull and making this all so unbearable, actually i am quite tired now! what if i lay down? I think i should… Oh there she is! im drawn to this thing, is she following me? I cant turn this off! Am i in pain? Now that i think about it i am in pain, i haven’t eaten in days! Oh but the light, i must go. I drone on, back to my cottage, thinking of foraging later but i see her near the door. Except this time i REALLY know who is is. It is my dear Lillian! I make a break for it, like a greyhound, and make it inside in now time at all. “Lillian!” I scream. I am sobbing now “LILLIAN!,” I screech, over and over. Dazed, confused, and scared, i turn once again, just as the wind drops. And there she is, Except this time I don’t know who is really is. All I know is the gown, live for the gown, live, to live is for the… she says, “finally, you’re home my love!” as i dropped, motionless to the floor.</p>
        <p>some time has passed, but all i know is that I woke up to the coldest sweat of my Life.</p>

        <?php include '../footer.php'; ?>
    </div>
</body>
</html>